version: '3'
services:
  web:
    image: ${IMAGE_NAME}
    build: .
    environment:
      NODE_ENV: ${ENV_APP}
    env_file:
      - .env
    ports:
      - ${IMAGE_PORT}:${SERVER_PORT}
    links:
      - mongo
  mongo:
    image: ${MONGO_IMAGE_NAME}
    container_name: ${MONGO_CONTAINER_NAME}
    volumes:
      - ${MONGO_VOLUME_PATH}
    ports:
      - ${MONGO_IMAGE_PORT}:${MONGO_PORT}
